---
- hosts: all
  become: true


  tasks:
    - name: Go to docker-compose
      command: docker-compose pull
      args:
        chdir: DockerCompose/
    - name: Runnig Docker-compose
      command: docker-compose up --build -d
      args:
        chdir: DockerCompose/
