name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
# ----------------LOGIN TO DOCKER ---------------------------
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Build and push to docker
      id: docker_build
      uses:  docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: divyanshuvijay43/student_front:latest
